
import Link from 'next/link'
import './globals.css'
import { LogOutBtn } from '../LoginBtn/LogOutBtn'
import  LoginBtn  from '../LoginBtn/LoginBtn'
import  SignupBtn  from '../LoginBtn/SignupBtn'
import '@/css/navbar.css';
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
      <div className="navbar">
      <div className='logo'>
        <span>#cafe</span>
      </div>
      <div className='menu'>
      <Link href="/">Home</Link> 
      <Link href="/mapAPI">Cafe Map</Link>
      <Link href="/cafeNews">Cafe News</Link>
      <Link href="/editTags"># Edit Page</Link>
      </div>
      <div className='loginSignup-Btn'>
      { 
      session ? (
        <span>
          {session.user.name} <LogOutBtn />
        </span>
      ) : (
        <span>
          <LoginBtn />
          <SignupBtn />
        </span>
      )
      }
      </div>
      </div>
      {children}</body>
    </html>
  )
}